# Generated by Django 2.0.4 on 2018-05-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameBoby',
            new_name='GameBoy',
        ),
    ]
